stages:
  - qa-install
  - qa-test
  - qa-build
  - qa-deploy
  - pro-install
  - pro-test
  - pro-build
  - pro-deploy

qa-install-job:
  stage: qa-install
  tags: 
    - qa-app-ventanilla
  only:
    - qa
  script:
    - echo "QA Install Job Here | To Do"

qa-test-job:
  stage: qa-test
  tags: 
    - qa-app-ventanilla
  only:
    - qa
  script:
    - echo "QA Test Job Here | To Do"

qa-build-job:
  stage: qa-build
  tags: 
    - qa-app-ventanilla
  only:
    - qa
  script:
    - echo "QA Build Job Here | To Do"

qa-deploy-job:
  stage: qa-deploy
  tags: 
    - qa-app-ventanilla
  only:
    - qa
  script:
    - echo "QA Deploy Job !!!!"
    - pwd
    - cd /home/gitlab-runner/src
    - sudo rm -rRf frontvim/
    - sudo git clone -b qa http://jlrosasp:M%404v3r1cK77@devops.guanajuato.gob.mx/Mariano_O/frontvim.git
    - sudo chown gitlab-runner:gitlab-runner -R frontvim/
    - cd /home/gitlab-runner/src/deployment-fullstack
    - source ../../.bash_profile
    - docker-compose -f docker-compose.qa.yml up --build -d qa-app-ventanilla_v2

pro-install-job:
  stage: pro-install
  tags: 
    - pro-app-ventanilla
  only:
    - main
  script:
    - echo "PROD Install Job Here | To Do"

pro-test-job:
  stage: pro-test
  tags: 
    - pro-app-ventanilla
  only:
    - main
  script:
    - echo "PROD Test Job Here | To Do"

pro-build-job:
  stage: pro-build
  tags: 
    - pro-app-ventanilla
  only:
    - main
  script:
    - echo "PROD Build Job Here | To Do"

pro-deploy-job:
  stage: pro-deploy
  tags: 
    - pro-app-ventanilla
  only:
    - main
  script:
    - echo "PROD Deploy Job !!!"
    - cd /home/gitlab-runner/src
    - sudo rm -rRf frontvim/
    - sudo git clone -b main  http://jlrosasp:M%404v3r1cK77@devops.guanajuato.gob.mx/Mariano_O/frontvim.git
    - sudo chown gitlab-runner:gitlab-runner -R frontvim/
    - cd /home/gitlab-runner/src/deployment-fullstack
    - source ../../.bash_profile
    - docker-compose -f docker-compose.prod.yml up --build -d pro-app-ventanilla_v2
